export const adjectives = [
  {
    word: "しずか",
    kanji: "静か",
    meaning: "quiet",
    groupId: "b5dccae3-d8c1-469e-9d54-3633145de282",
  },
  {
    word: "きれい",
    kanji: "綺麗",
    meaning: "beautiful",
    groupId: "b5dccae3-d8c1-469e-9d54-3633145de282",
  },
  {
    word: "きらい",
    meaning: "dislike",
    groupId: "b5dccae3-d8c1-469e-9d54-3633145de282",
  },
  {
    word: "へた",
    meaning: "unskilled",
    groupId: "b5dccae3-d8c1-469e-9d54-3633145de282",
  },
  {
    word: "やさしい",
    kanji: "優しい",
    meaning: "kind",
    groupId: "2c81d0c0-d73a-4185-a0f1-f4e6ff150bdc",
  },
  {
    word: "だいじ",
    kanji: "大事",
    meaning: "important",
    groupId: "b5dccae3-d8c1-469e-9d54-3633145de282",
  },
  {
    word: "べんり",
    kanji: "便利",
    meaning: "convenient",
    groupId: "b5dccae3-d8c1-469e-9d54-3633145de282",
  },
  {
    word: "いそがしい",
    kanji: "忙しい",
    meaning: "busy",
    groupId: "2c81d0c0-d73a-4185-a0f1-f4e6ff150bdc",
  },
  {
    word: "あたらしい",
    kanji: "新しい",
    meaning: "new",
    groupId: "2c81d0c0-d73a-4185-a0f1-f4e6ff150bdc",
  },
  {
    word: "おおきい",
    kanji: "大きい",
    meaning: "big",
    groupId: "2c81d0c0-d73a-4185-a0f1-f4e6ff150bdc",
  },
  {
    word: "ちいさい",
    kanji: "小さい",
    meaning: "small",
    groupId: "2c81d0c0-d73a-4185-a0f1-f4e6ff150bdc",
  },
  {
    word: "すごい",
    meaning: "amazing",
    groupId: "2c81d0c0-d73a-4185-a0f1-f4e6ff150bdc",
  },
  {
    word: "たかい",
    kanji: "高い",
    meaning: "high",
    groupId: "2c81d0c0-d73a-4185-a0f1-f4e6ff150bdc",
  },
  {
    word: "やすい",
    kanji: "安い",
    meaning: "cheap",
    groupId: "2c81d0c0-d73a-4185-a0f1-f4e6ff150bdc",
  },
  {
    word: "つよい",
    kanji: "強い",
    meaning: "strong",
    groupId: "2c81d0c0-d73a-4185-a0f1-f4e6ff150bdc",
  },
  {
    word: "よわい",
    kanji: "弱い",
    meaning: "weak",
    groupId: "2c81d0c0-d73a-4185-a0f1-f4e6ff150bdc",
  },
  {
    word: "たのしい",
    kanji: "楽しい",
    meaning: "fun",
    groupId: "2c81d0c0-d73a-4185-a0f1-f4e6ff150bdc",
  },
  {
    word: "つまらない",
    kanji: "詰まらない",
    meaning: "boring",
    groupId: "2c81d0c0-d73a-4185-a0f1-f4e6ff150bdc",
  },
];
///////////////////////////////////////////////////////////////////////////
export const food = [
  { noun: "にんじん", kanji: "人参", meaning: "carrot", category: "food" },
  {
    noun: "じゃがいも",
    kanji: "じゃが芋",
    meaning: "potato",
    category: "food",
  },
  { noun: "たまねぎ", kanji: "玉葱", meaning: "onion", category: "food" },
  { noun: "きゅうり", kanji: "胡瓜", meaning: "cucumber", category: "food" },
  { noun: "トマト", meaning: "tomato", category: "food" },
  { noun: "りんご", kanji: "林檎", meaning: "apple", category: "food" },
  { noun: "バナナ", meaning: "banana", category: "food" },
  { noun: "いちご", kanji: "苺", meaning: "strawberry", category: "food" },
  {
    noun: "みかん",
    kanji: "蜜柑",
    meaning: "mandarin orange",
    category: "food",
  },
  { noun: "ぶどう", meaning: "grape", category: "food" },
  { noun: "さくらんぼ", meaning: "cherry", category: "food" },
  { noun: "かぼちゃ", meaning: "pumpkin", category: "food" },
  { noun: "ぎゅうにゅう", kanji: "牛乳", meaning: "milk", category: "food" },
  { noun: "パン", meaning: "bread", category: "food" },
  { noun: "ごはん", kanji: "ご飯", meaning: "rice", category: "food" },
  { noun: "にく", kanji: "肉", meaning: "meat", category: "food" },
  { noun: "さかな", kanji: "魚", meaning: "fish", category: "food" },
  { noun: "チーズ", meaning: "cheese", category: "food" },
  { noun: "たまご", kanji: "卵", meaning: "egg", category: "food" },
  { noun: "ヨーグルト", meaning: "yogurt", category: "food" },
];
//////////////////////////////////////////////////////////////////////////
export const transportation = [
  {
    noun: "ひこうき",
    kanji: "飛行機",
    meaning: "airplane",
    category: "transportation",
  },
  {
    noun: "でんしゃ",
    kanji: "電車",
    meaning: "train",
    category: "transportation",
  },
  {
    noun: "ちかてつ",
    kanji: "地下鉄",
    meaning: "subway",
    category: "transportation",
  },
  { noun: "バス", meaning: "bus", category: "transportation" },
  { noun: "タクシー", meaning: "taxi", category: "transportation" },
  {
    noun: "じてんしゃ",
    kanji: "自転車",
    meaning: "bicycle",
    category: "transportation",
  },
  { noun: "えき", kanji: "駅", meaning: "station", category: "transportation" },
  {
    noun: "ばすてい",
    kanji: "バス停",
    meaning: "bus stop",
    category: "transportation",
  },
  {
    noun: "くうこう",
    kanji: "空港",
    meaning: "airport",
    category: "transportation",
  },
  {
    noun: "しんごう",
    kanji: "信号",
    meaning: "traffic light",
    category: "transportation",
  },
  {
    noun: "こうさてん",
    kanji: "交差点",
    meaning: "intersection",
    category: "transportation",
  },
  {
    noun: "みち/どうろ",
    kanji: "道/道路",
    meaning: "road",
    category: "transportation",
  },
];
/////////////////////////////////////////////////////////////////////////
export const occupations = [
  { noun: "いし", kanji: "医師", meaning: "doctor", category: "occupation" },
  {
    noun: "かんごし",
    kanji: "看護師",
    meaning: "nurse",
    category: "occupation",
  },
  {
    noun: "べんごし",
    kanji: "弁護士",
    meaning: "lawyer",
    category: "occupation",
  },
  {
    noun: "りょうりにん",
    kanji: "料理人",
    meaning: "chef",
    category: "occupation",
  },
  {
    noun: "じつぎょうか",
    kanji: "実業家",
    meaning: "businessperson",
    category: "occupation",
  },
  {
    noun: "けいさつかん",
    kanji: "警察官",
    meaning: "police officer",
    category: "occupation",
  },
  {
    noun: "しょうぼうし",
    kanji: "消防士",
    meaning: "firefighter",
    category: "occupation",
  },
  {
    noun: "ぎじゅつしゃ",
    kanji: "技術者",
    meaning: "engineer",
    category: "occupation",
  },
  {
    noun: "こうむいん",
    kanji: "公務員",
    meaning: "civil servant",
    category: "occupation",
  },
  {
    noun: "かいけいし",
    kanji: "会計士",
    meaning: "accountant",
    category: "occupation",
  },
];
/////////////////////////////////////////////////////////////////////////////////////////////
export const relationships = [
  {
    noun: "おとうさん",
    kanji: "お父さん",
    meaning: "father",
    category: "relationship",
  },
  {
    noun: "おかあさん",
    kanji: "お母さん",
    meaning: "mother",
    category: "relationship",
  },
  {
    noun: "おとうと",
    kanji: "弟",
    meaning: "younger brother",
    category: "relationship",
  },
  {
    noun: "あに",
    kanji: "兄",
    meaning: "older brother",
    category: "relationship",
  },
  {
    noun: "いもうと",
    kanji: "妹",
    meaning: "younger sister",
    category: "relationship",
  },
  {
    noun: "あね",
    kanji: "姉",
    meaning: "older sister",
    category: "relationship",
  },
  {
    noun: "おじさん",
    kanji: "叔父さん",
    meaning: "uncle",
    category: "relationship",
  },
  {
    noun: "おばさん",
    kanji: "叔母さん",
    meaning: "aunt",
    category: "relationship",
  },
  {
    noun: "いとこ",
    kanji: "従兄弟",
    meaning: "cousin",
    category: "relationship",
  },
  {
    noun: "おじいさん",
    kanji: "お祖父さん",
    meaning: "grandfather",
    category: "relationship",
  },
  {
    noun: "おばあさん",
    kanji: "お祖母さん",
    meaning: "grandmother",
    category: "relationship",
  },
  {
    noun: "ひとりっこ",
    kanji: "一人っ子",
    meaning: "only child",
    category: "relationship",
  },
  {
    noun: "しんせき",
    kanji: "親戚",
    meaning: "relative",
    category: "relationship",
  },
  { noun: "むすこ", kanji: "息子", meaning: "son", category: "relationship" },
  {
    noun: "むすめ",
    kanji: "娘",
    meaning: "daughter",
    category: "relationship",
  },
];
////////////////////////////////////////////////////////////////////////
export const academics = [
  {
    noun: "すうがく",
    kanji: "数学",
    meaning: "mathematics",
    category: "academics",
  },
  { noun: "えいご", kanji: "英語", meaning: "English", category: "academics" },
  { noun: "れきし", kanji: "歴史", meaning: "history", category: "academics" },
  { noun: "かがく", kanji: "科学", meaning: "science", category: "academics" },
  { noun: "ちり", kanji: "地理", meaning: "geography", category: "academics" },
  { noun: "ぶつり", kanji: "物理", meaning: "physics", category: "academics" },
  {
    noun: "かがく",
    kanji: "化学",
    meaning: "chemistry",
    category: "academics",
  },
  {
    noun: "せいぶつがく",
    kanji: "生物学",
    meaning: "biology",
    category: "academics",
  },
  {
    noun: "しんりがく",
    kanji: "心理学",
    meaning: "psychology",
    category: "academics",
  },
  {
    noun: "せいじがく",
    kanji: "政治学",
    meaning: "political science",
    category: "academics",
  },
  {
    noun: "けいざいがく",
    kanji: "経済学",
    meaning: "economics",
    category: "academics",
  },
  {
    noun: "ぶんがく",
    kanji: "文学",
    meaning: "literature",
    category: "academics",
  },
  {
    noun: "げんごがく",
    kanji: "言語学",
    meaning: "linguistics",
    category: "academics",
  },
  {
    noun: "てつがく",
    kanji: "哲学",
    meaning: "philosophy",
    category: "academics",
  },
];
